### ISSUE TITLE
Example gitlab.ci?

### ISSUE THREAD

**Issue by treystout** [bentolor/docker-dind-awscli#1]
Thanks for making this image. I'm a little confused though. Should this image be used as the top level `image: ...` for the config file or in the individual build step that requires usage of `aws`?

**Comment by bentolor** [comment]
I added an example coed nipped for Gitlab CI to illustrate it.

It's just a _replacement_ image for the places where you'd used `docker:dind` but then fail to i..e push it to AWS due to missing `awscli`

**Comment by bentolor** [comment]
After even stating the wrong hint on my own (it's a replacement for `docker:stable`, not  `docker:dind`) I added another prominent note in the readme.

The image name I've chosen is misleading: But I wanted to have the keywords in it so people are able to find it. 

Sorry & thanks for the feedback, @treystout : This is a typical pitfall I wasn't able to see on my own.

**Comment by treystout** [comment]
Works like a charm, thank you again for this! It saved me a lot of headache.
![image](https://user-images.githubusercontent.com/751002/85588621-76f54300-b608-11ea-82b4-5225c9d19e9d.png)
