### ISSUE TITLE
would it be possible to add bash to the image?

### ISSUE THREAD

**Issue by treystout** [bentolor/docker-dind-awscli#2]
Thank you for this image we use it for all our CI builds. However a new Makefile target in CI needs to run inside `bash` not `sh` and bash isn't available.

**Comment by bentolor** [comment]
Dear @treystout!  Alpine puts much effort to stay as minimal as possible to provide very small images. Therefore I hesitate to add it to the mainline. Honestly I suspect, bash easily might not be the only dependency missing.

Nevertheless, I have two proposals to fix your issue quickly:

### Use a dedicated version I prepared for you

I prepared a special [`docker-dind-awscli:2.1.36-bash`](https://hub.docker.com/layers/bentolor/docker-dind-awscli/2.1.36-bash/images/sha256-9e93ca31be33259bb2ad952bd4420c370765ca706b515099afea9d65851d5a03?context=repo) version. This includes `bash` installed in the way below:

```
$ sudo docker run --rm  bentolor/docker-dind-awscli:2.1.36-bash /bin/bash --version
GNU bash, version 5.0.17(1)-release (x86_64-alpine-linux-musl)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

or 

### Install `bash` on demand

    apk --no-cache add bash

The side effect, that this will need to download ~24MB on each run. 

Hope this help!

**Comment by bentolor** [comment]
Ok – I just rechecked: The resulting image is much larger than anticipated anyways. So please give me a hint if it works for you and I can add `bash` permanently.

**Comment by bentolor** [comment]
Beginning with the lastest `lastest` and `2.2.20` and newer, the image now is prebundled with bash and interactive root sessions now `/bin/bash` as default shell, too.
