### ISSUE TITLE
How to run it in Jenkins Pipeline

### ISSUE THREAD

**Issue by teguhbudhi13** [bentolor/docker-dind-awscli#7]
Hi im trying to run this on my jenkins pipeline but so far no luck, usually i just use docker dind with pipeline below to push it to my harbor registry but right now want to test it to aws ecr so i need awscli to login first
can you try to help me, this is my pipeline on my Jenkinsfile that working right now to harbor registry

podTemplate(yaml: '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: docker
    image: docker:20.10-dind
    args:
    - "--mtu=1450"
    securityContext:
      privileged: true
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ""
''') {
    node(POD_LABEL) {
        stage('docker build')
            container('docker') {
            sh 'docker login coreharbor.test.com -u test -p Passw0rd'
            }
    }
    }

**Comment by bentolor** [comment]
What's the issue? Simply replacing the image should work IMHO

**Comment by bentolor** [comment]
Nota bene: replacing the docker:latest not the _docker:dind_ instance!

**Comment by teguhbudhi13** [comment]
this is the result if im replacing the pipeline with that
podTemplate(yaml: '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: docker
    image: bentolor/docker-dind-awscli
    args:
    - "--mtu=1450"
''') {
    node(POD_LABEL) {
        stage('docker build')
            container('docker') {
            sh 'docker login coreharbor.test.com -u test -p Passw0rd'
            }
    }
    }
    
    
![image](https://user-images.githubusercontent.com/50268422/202617247-90bd8729-a292-4998-ad85-35fa1e3eebc7.png)

**Comment by bentolor** [comment]
It seems my comment was not clear:

You need two containers:
- docker:dind 
- bentolor/docker-dind-awscli

The later linked to the dind instance used to execute the docker daemon instance.

See ["solution 3" here](https://www.tiuweehan.com/blog/2020-09-10-docker-in-jenkins-in-docker/) for background information how dind actually works.

**Comment by bentolor** [comment]
In your case you seem to execute the docker commands directly inside the daemon container. Potentially building a variant of this image based on "docker:dind" vs. "docker:latest" could produce a drop-in replacement for your use case. Let me check

**Comment by bentolor** [comment]
@teguhbudhi13 I built also a `dind` variant for you. Can you try, if in your first example replacing `docker:20.10-dind` with `bentolor/docker-dind-awscli:dind` works for you?

**Comment by bentolor** [comment]
@teguhbudhi13 Please read the update `README.md` wich should explain the reasoning behind that.

**Comment by teguhbudhi13** [comment]
thanks dude it really help me a lot
for futher reference this is what you can use in one jenkins pipeline in kubernetes


podTemplate(yaml: '''
apiVersion: v1
kind: Pod
metadata:
  name: dockertests
  labels:
    name: dockertests
spec:
  volumes:
      - name: dockertests-pv
        persistentVolumeClaim:
          claimName: dockertests-pv-claim
  containers:
    - name: dockertests
      image: bentolor/docker-dind-awscli:dind
      resources:
          limits:
            cpu: 16
          requests:
            cpu: 4
      volumeMounts:
        - name: dockertests-pv
          mountPath: /tmp/
      args:
      - "--mtu=1450"
      securityContext:
        privileged: true
      env:
      - name: DOCKER_TLS_CERTDIR
        value: ""
''') 
{
        node(POD_LABEL) {
        stage('gitclone') {
        <Use your git clone command here>
            }
        stage('docker build')
            container('dockertests') {
            sh 'docker build -t (your image name) . && docker push (your image name)'
            }
    }
    }
    
use PV if you want to save for cache, so it can build faster

and also @bentolor can i ask the Dockerfile for image bentolor/docker-dind-awscli:dind , so i can use it for futher reference and contribute also

Thanks a lot before

**Comment by teguhbudhi13** [comment]
The Dockerfile in your repo its not working if im build it on my machine

**Comment by teguhbudhi13** [comment]
nevermind i got it just read your replace docker to dind version in Dockerfile
