### ISSUE TITLE
`dotnet publish` inside `docker buildx` failing since update to Docker 24.0.5

### ISSUE THREAD

**Issue by FacioRatio** [bentolor/docker-dind-awscli#8]
dotnetpublish now failing since update to Docker 24.0.5:
```
[publish 1/1] RUN dotnet publish "Blahblah.csproj" -c Release -o /app/publish
#19 ERROR: failed to prepare azirp0wp7qd8ea9ujnn3hjs4a: invalid argument
```

**Comment by bentolor** [comment]
Hmmm. Some more context? Are you depending on something particular in the image?

I saw that the docker base image underwent some significant changes also visible in the image size.

**Comment by FacioRatio** [comment]
Pretty basic dockerfile:

```
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["./backend/Blah.Api", "Blah.Api/"]
COPY ["./backend/Blah.Domain", "Blah.Domain/"]
COPY ["./backend/Blah.Infrastructure", "Blah.Infrastructure/"]
RUN dotnet restore "Blah.Api/Blah.Api.csproj"
COPY . .
WORKDIR "/src/Blah.Api"
RUN dotnet build "Blah.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Blah.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Blah.Api.dll"]
```

If I peg my .gitlab-ci.yml to bentolor/docker-dind-awscli:2.8.13 then everything is fine.

Here is some more context from the build log in Gitlab:

```
...
#18 7.830 Build succeeded.
#18 7.831     0 Warning(s)
#18 7.831     0 Error(s)
#18 7.832 
#18 7.832 Time Elapsed 00:00:06.79
#18 DONE 11.2s
#6 [build 1/9] FROM mcr.microsoft.com/dotnet/sdk:6.0@sha256:894872a219bfa6d186453ce5cdfac8269f4b45b410dd356a5dd9df8ad48f4d83
#6 ...
#19 [publish 1/1] RUN dotnet publish "Blah.Api.csproj" -c Release -o /app/publish
#19 ERROR: failed to prepare azirp0wp7qd8ea9ujnn3hjs4a: invalid argument
#6 [build 1/9] FROM mcr.microsoft.com/dotnet/sdk:6.0@sha256:894872a219bfa6d186453ce5cdfac8269f4b45b410dd356a5dd9df8ad48f4d83
------
 > [publish 1/1] RUN dotnet publish "Blah.Api.csproj" -c Release -o /app/publish:
------
WARNING: buildx: git was not found in the system. Current commit information was not captured by the build
ERROR: failed to solve: failed to solve with frontend dockerfile.v0: failed to build LLB: failed to prepare azirp0wp7qd8ea9ujnn3hjs4a: invalid argument
```

**Comment by bentolor** [comment]
So to sum up:

Your `docker buildx` as part of your `.gitlab-ci.yml` executes successfully in older `docker:stable` now fails in current `docker` stable?

That's strange. Seems to be in issue of the upstream image. 

* Can you verify this by running your docker buildx directly in `docker:latest`? 
* If yes, report upstream please
* Increasing log level might help to understand better where `buildx` fails

**Comment by bentolor** [comment]
There is a similar issues at https://github.com/docker-library/docker/issues/434 reporting a similar, suddenly failing build starting with `docker:24.0.4`. 

I just published an updated `docker-dind-awscli:latest` and ``docker-dind-awscli:2.13.4-docker-24.0.3`  which downgrades to `docker:24.0.3`. 

Does this solve this issue, @FacioRatio ? In that case it's clearly an upstream issue and I'd suggest to chip in on the upstream project. It seems their latest update breaks a few more things for others as well.

**Comment by bentolor** [comment]
As no activities happened on this issue I assume it has resolved or is stale. Closing, as this seems to be an upstream issue.

**Comment by FacioRatio** [comment]
Never found anything upstream. Never resolved. Just pegging to 2.8.13. Problem for whenever things break again in the unknown future.
